version: '3.7'
services:
  nginx:
    build:
      context: ./container/nginx
      dockerfile: Dockerfile
    volumes:
      - "./web/src:/var/www/joomla/"
    ports:
      - "80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./container/php
      dockerfile: Dockerfile
    volumes:
      - "./web/src:/var/www/joomla/"
    depends_on:
      - db

  db:
    build:
      context: ./container/db
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: "joomla"
      MYSQL_USER: "root"
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  host:
    container_name: my-host-container
    build:
      context: ./container/host
      dockerfile: Dockerfile
      args:
        SSH_ROOT_PASS: secret
    ports:
      - "22"