// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/sepuka/chat/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// Cloud is an autogenerated mock type for the Cloud type
type Cloud struct {
	mock.Mock
}

// Run provides a mock function with given fields: pool, cmd
func (_m *Cloud) Run(pool *domain.Pool, cmd domain.RemoteCmd) ([]byte, error) {
	ret := _m.Called(pool, cmd)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(*domain.Pool, domain.RemoteCmd) []byte); ok {
		r0 = rf(pool, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Pool, domain.RemoteCmd) error); ok {
		r1 = rf(pool, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
